### ISSUE TITLE
@Indexed on enum fields

### ISSUE THREAD

**Issue by michaelstiller78** [redis/redis-om-spring#215]
Hi everyone,

we have a problem with a field with an enum type annotated with "@Indexed". There is no "Index" created for this field.

If a reference field (referencing another class) is annotated with "@Indexed", then there is no index created either. Only if the referenced class contains fields annotated with "@Indexed", then there are combined indices created.

Maybe the problem is, that an enum is treated like a class and the enum does not contain "@Indexed" fields!?

Could you please check on this and provide a solution, so that enum fields can be used when searching for data?

Thank you and regards

Michael

**Comment by bsbodden** [comment]
Can you post a sample app to use as a reference? Currently, Enums are not indexed. We could potentially index them as `TAG`s but it'll be nice to have an actual real-world example.

`@Reference` fields and search might require some special treatment since across-collections indexing is not clearly defined.
