### ISSUE TITLE
Implement Sentinel support

### ISSUE THREAD

**Issue by shannonantony** [redis/redis-om-spring#227]
I am struggling to run the demos in redis-om-spring project locally. 

for example, running roms-documents demo is giving JedisConnectException. I am modifying the sample to run with my Sentinel setup as below

@Bean
	public JedisConnectionFactory jedisConnectionFactory() {
		RedisSentinelConfiguration sentinelConfig = new RedisSentinelConfiguration().master("mymaster")
				.sentinel("x.x.x.x", 26379).sentinel("x.x.x.y", 26379).sentinel("x.x.x.z", 26379);
		return new JedisConnectionFactory(sentinelConfig);
	}

can you please let me know the steps to run the samples with Sentinel setup.

Appreciate your help

thanks

Jay

**Comment by bsbodden** [comment]
We're testing the Sentinel's setups, stay tuned...

**Comment by anyili** [comment]
I have a similar issue, I think it is due to the jedis 4.3.2 doesn't support sentinel pool, and RedisModulesClient making a pool only using StandaloneConfiguration. So if you pass the sentinel connection, the StandaloneConfiguration will return null. The jedis socket creates connection to localhost 6379. I am having a PR to fix it. @bsbodden  let me know if you like the PR

**Comment by bsbodden** [comment]
Regression?
