### ISSUE TITLE
SearchStreamImpl returnFields not working for NonIndexed and nested Indexed fields in 0.8.6

### ISSUE THREAD

**Issue by rpjtesting** [redis/redis-om-spring#327]
SearchStreamImpl preareQuery method internally uses getSearchAlias() method on metamodel to return specific fields in search. It won't work for fields which are not indexed or fields which are nested and Indexed.

**Comment by bsbodden** [comment]
Hi, I am using EntityStream for fetching and filtering data. My json document contains few non-indexed and indexed nested fields. 

project(Metamodel<> ....) method from EntityStream was used to return specific field from json documents. But only Indexed fields were returned in redis response. 

I think the prepareQuery() method of SearchStreamImpl should use foi.getJsonPath() instead of foi.getSearchAlias(). 

Please suggest if any alternative method is there for returning non-indexed fields. 

Below is prepareQuery method from SearchStreamImpl class

```
Query prepareQuery() {
    Query query;

    if (knnPredicate != null) {
      query = new Query(knnPredicate.apply(rootNode).toString());
      query.addParam(knnPredicate.getBlobAttributeName(), knnPredicate.getBlobAttribute());
      query.addParam("K", knnPredicate.getK());
      query.dialect(2);
    } else {
      query = (rootNode.toString().isBlank()) ? new Query() : new Query(rootNode.toString());
      query.dialect(dialect);
    }

    query.limit(skip != null ? skip.intValue() : 0, limit != null ? limit.intValue() : MAX_LIMIT);

    if (sortBy != null) {
      SortedField sortField = sortBy;
      query.setSortBy(sortField.getField(), sortField.getOrder().equals("ASC"));
    }

    if (onlyIds) {
      query.returnFields(idField.getName());
    } else if (!projections.isEmpty()) {
      var returnFields = projections.stream() //
          .map(foi -> ObjectUtils.isCollection(foi.getTargetClass()) ? "$." + foi.getSearchAlias() : foi.getSearchAlias())
          .collect(toCollection(ArrayList::new));
      returnFields.add(idField.getName());

      query.returnFields(returnFields.toArray(String[]::new));
    }

    return query;
  }
  ```

**Comment by rpjtesting** [comment]
Also, if returnFields are set while preparing query, the response returned is null with IllegalAccessException, as all fields in my entity are private. Please add support for private fields as well.
