### ISSUE TITLE
When to use @EnableRedisEnhancedRepositories vs @EnableRedisDocumentRepositories

### ISSUE THREAD

**Issue by shannonantony** [redis/redis-om-spring#408]
@bsbodden Thanks for your great work. Just curious to know when we should go for @EnableRedisEnhancedRepositories vs @EnableRedisDocumentRepositories based design?

In the current project I'm engaged in, I have the flexibility to choose between either approach, as the data originates from a relational database. However, I would like to weigh the advantages and disadvantages of each method before making a decision.

Appreciate your help

thanks

Jay

**Comment by bsbodden** [comment]
Hey @shannonantony - that's a good question... I tend to prefer JSON since the impedance mismatch with relation data will be lower. With Hashes you 1-level. flat, DTO-like entities with JSON you get a tree structure that gives you the ability to have more depth to your objects. So the questions typically boils down to is this a flat object and will always be flat, then Hashes, they are more compact, but if your objects have other non-Java native objects in them, then JSON. Hope that helps.

**Comment by shannonantony** [comment]
thanks a lot @bsbodden
