### ISSUE TITLE
reative redis API via lettuce?

### ISSUE THREAD

**Issue by xmlking** [redis/redis-om-spring#6]
when attempted to use with `ReactiveRedisTemplate`, getting   `JedisConnectionFactory` not found error. 

I understand this project is in development. 
wonder if  you have plans to enable Reactive API (ReactiveCrudRepository etc) via lettuce?

```gradle
    implementation("org.apache.commons:commons-pool2")
    implementation("io.lettuce:lettuce-core")
    implementation("com.redis.om:redis-om-spring:0.1.0-SNAPSHOT")
```

```
 Unsatisfied dependency expressed through method 'redisModulesClient' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.data.redis.connection.jedis.JedisConnectionFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

**Comment by bsbodden** [comment]
@xmlking currently we are only in non-reactive mode using Jedis under the covers. We are looking into the dual the Jedis/Lettuce support like Spring Data Redis.

**Comment by xmlking** [comment]
Thanks a lot @bsbodden for making this available for early evaluators. 
I will keep testing and share the feedback.

**Comment by patpatpat123** [comment]
Hello Brian, 

Hope this post finds you well.
First of all, I wanted to say thanks for your cool talk at Devoxx Belgium 2022. It was interesting and clear.

Now couple of hours away from 2023, one year after the original post from this thread in 2021, I was wondering if you could provide a bit if update on the reactive support for redis-om.

Reactive apps, especially Spring Webflux, are gaining in popularity fast, many teams are migrating to this new paradigm.
Would it be possible to offer reactive support for redis-om-spring please?

For instance (this is just for example) in your talk, instead of returning an Iterable of FictionalCharacter, to return a Flux of FictionalCharacter?

Having full support for Flux and Mono from redis-om-spring will definitely be a plus.
Currently, our team is using ```spring-boot-starter-data-redis-reactive```, which is great, but some additional features from Redis Stack and redis-om-spring are very interesting. I would be great to be able to have reactive support.

Thank you and the best for 2023 @bsbodden
